# Generated by Django 5.1.1 on 2024-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_listchai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listchai',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
